# Build ChatList.exe and Inno Setup installer.
# Version is read only from version.py.

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

$python = if (Test-Path ".\.venv\Scripts\python.exe") {
    ".\.venv\Scripts\python.exe"
} else {
    "python"
}

$version = & $python -c "from version import __version__; print(__version__)"
if (-not $version) {
    throw "Failed to read __version__ from version.py"
}
Write-Host "App version: $version"

@(
    "; Generated by build.ps1 from version.py - do not edit."
    "#define MyAppVersion `"$version`""
) | Set-Content -Path ".\version.iss" -Encoding ASCII

Write-Host "Building exe (PyInstaller)..."
& $python -m PyInstaller --noconfirm .\ChatList.spec
if ($LASTEXITCODE -ne 0) {
    throw "PyInstaller failed with exit code $LASTEXITCODE"
}

$iscc = $null
$programFilesX86 = [Environment]::GetFolderPath("ProgramFilesX86")
$candidates = @(
    (Join-Path $env:LocalAppData "Programs\Inno Setup 6\ISCC.exe"),
    (Join-Path $programFilesX86 "Inno Setup 6\ISCC.exe"),
    (Join-Path $env:ProgramFiles "Inno Setup 6\ISCC.exe")
)
foreach ($path in $candidates) {
    if (Test-Path $path) {
        $iscc = $path
        break
    }
}
if (-not $iscc) {
    $cmd = Get-Command iscc -ErrorAction SilentlyContinue
    if ($cmd) {
        $iscc = $cmd.Source
    }
}

if (-not $iscc) {
    Write-Warning "Inno Setup (ISCC.exe) not found - installer was not built."
    Write-Host "exe: .\dist\ChatList.exe"
    exit 0
}

New-Item -ItemType Directory -Force -Path ".\installer" | Out-Null
Write-Host "Building installer with: $iscc"
& $iscc ".\installer.iss"
if ($LASTEXITCODE -ne 0) {
    throw "ISCC failed with exit code $LASTEXITCODE"
}

$installer = ".\installer\ChatList-Setup-$version.exe"
Write-Host "Done:"
Write-Host "  exe:       .\dist\ChatList.exe"
Write-Host "  installer: $installer"
